sale_exception: keep detail of exceptions on lines
So we can:

* display the lines with an exception in red
* show the exception messages when we click on a line

It's a huge usability improvement when users have dozens or hundreds of
lines.